### ISSUE TITLE
Successful WP login does not save to text.

### ISSUE THREAD

**Issue by IssueThrowaway** [Moham3dRiahi/XBruteForcer#10]
I tested on a WP setup I have and when it tries the correct password, the app just closes.  Does not save to Result.txt even when I created that textfile in the directory.

Please look into this. 

Thanks!

**Comment by americanitunes101** [comment]
Bro. I paid for XAttacker v10 Lifetime Key off your Shoppy.gg — Order ID: 6796fc84-b0e8-4de2-bc2a-9874897d5cfc
But the .zip it delivered for me to download was password protected, and no password was given. 
I contacted you on Telegram @moham3driahi, and you said you’d fix the problem when you got home. 
Then you delete the Telegram chat and don’t respond to me? 

What’s the go? I paid $100 for your script. Why are not delivering the product I paid for?  And now you’re deleting my comments?
 Please contact me via email at pmmailmate@pm.me

**Comment by americanitunes101** [comment]
Bro. I paid for XAttacker v10 Lifetime Key off your Shoppy.gg — Order ID: 6796fc84-b0e8-4de2-bc2a-9874897d5cfc
But the .zip it delivered for me to download was password protected, and no password was given. 
I contacted you on Telegram @moham3driahi, and you said you’d fix the problem when you got home. 
Then you delete the Telegram chat and don’t respond to me? 

What’s the go? I paid $100 for your script. Why are not delivering the product I paid for?  And now you’re deleting my comments?
 Please contact me via email at pmmailmate@pm.me
