### ISSUE TITLE
Will this code work in Android on a pop-up box? Or just urls? 

### ISSUE THREAD

**Issue by l1ntbag** [Moham3dRiahi/XBruteForcer#13]
Will this code work in Android on a pop-up box? Or just urls? I need to try all my passwords in a lost password prompt in an app that has a pop-up prompt or by right click menu. Any ideas?

**Comment by UBISOFT-1** [comment]
Yes you can get live output from terminal, but a better approach is editing the code itself and integrating it into your application, If you need assistance in this matter you can contact me at: NamazVer2.0@gmail.com

**Comment by americanitunes101** [comment]
Bro. I paid for XAttacker v10 Lifetime Key off your Shoppy.gg — Order ID: 6796fc84-b0e8-4de2-bc2a-9874897d5cfc
But the .zip it delivered for me to download was password protected, and no password was given. 
I contacted you on Telegram @moham3driahi, and you said you’d fix the problem when you got home. 
Then you delete the Telegram chat and don’t respond to me? 

What’s the go? I paid $100 for your script. Why are not delivering the product I paid for?  And now you’re deleting my comments?
 Please contact me via email at pmmailmate@pm.me

**Comment by americanitunes101** [comment]
Bro. I paid for XAttacker v10 Lifetime Key off your Shoppy.gg — Order ID: 6796fc84-b0e8-4de2-bc2a-9874897d5cfc
But the .zip it delivered for me to download was password protected, and no password was given. 
I contacted you on Telegram @moham3driahi, and you said you’d fix the problem when you got home. 
Then you delete the Telegram chat and don’t respond to me? 

What’s the go? I paid $100 for your script. Why are not delivering the product I paid for?  And now you’re deleting my comments?
 Please contact me via email at pmmailmate@pm.me

**Comment by l1ntbag** [comment]
Already figured out a code with help in Python. Thanks though.

Sent from 
 
  On Thu, Oct 15, 2020 at 12:45 PM, ***@***.***> wrote:   


Yes you can get live output from terminal, but a better approach is editing the code itself and integrating it into your application, If you need assistance in this matter you can contact me at: ***@***.***
