### ISSUE TITLE
Errors In Windows

### ISSUE THREAD

**Issue by irneo** [Moham3dRiahi/XBruteForcer#6]
Hi
Thank You For Your Work
But
When Use This in Windows 
Shows Thees Error

 C:\Users\Lenovo\Downloads\Compressed\XBruteForcer>XBruteForcer.pl
      Unmatched right curly bracket at 
 C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 482, at end of line
    (Might be a runaway multi-line () string starting on line 475)
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 482, near "}"
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 624, near "}"
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 662, near "}"
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 685, near "}"
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 721, near "}"
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 776, near "}"
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 811, near "}"
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 843, near "}"
   syntax error at C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl line 897, near "}"
 C:\Users\Lenovo\Downloads\Compressed\XBruteForcer\XBruteForcer.pl has too many errors.

 C:\Users\Lenovo\Downloads\Compressed\XBruteForcer>

Thanks For Support

**Comment by Moham3dRiahi** [comment]
Thanks for reporting this issue. It should be fixed now in the latest commit 4805643
